// <auto-generated />
using System;
using BadanieKrwi.Data_Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BadanieKrwi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BadanieKrwi.Data_Base.Badania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bazofile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataBadania")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Eozynofile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HematokrytHtc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HemoglobinaHb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdKliniki")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<decimal>("Limfocyty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monocyty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Neutrofile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlytkiKrwiPLT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetikulocytyRC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RozpietoscRozkladuObjetosciErytrocytowRDWCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SredniaMasaHemoglobinyMCH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SredniaObjetoscErytrocytuMCV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SredniaObjetoscKrwiMPV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SrednieSteczenieHemoglobinyMCHC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StezenieErytrocytowRBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StezenieLeukocytowWBC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Badania");
                });

            modelBuilder.Entity("BadanieKrwi.Data_Base.Kliniki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lokalizacja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kliniki");
                });

            modelBuilder.Entity("BadanieKrwi.Data_Base.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownik");
                });
#pragma warning restore 612, 618
        }
    }
}
